### ISSUE TITLE
Unable to generate FakeIngressServer in diego-logging-client

### ISSUE THREAD

**Issue by winkingturtle-vmw** [cloudfoundry/go-loggregator#146]
Hello,

We generate [FakeIngressServer](https://github.com/cloudfoundry/diego-logging-client/blob/a6b1f3105a4523aa3c9ac0d6d7dcb9b97154c7a8/testhelpers/fake_ingress_server.go) in [diego-logging-client](https://github.com/cloudfoundry/diego-logging-client/blob/a6b1f3105a4523aa3c9ac0d6d7dcb9b97154c7a8/client_test.go#L48) for testing our Send*Log methods in the library. Since the [update protobuf PR #81](https://github.com/cloudfoundry/go-loggregator/pull/81/files#diff-19cfbc2551b3af958754b32c0569f804f6123bf1d032b70d346f1bd5aa2cb91dR122) we see that there is a new private method `mustEmbedUnimplementedIngressServer` that is making our FakeIngressServer implementation no longer valid. Can you please advice how we are suppose to solve this problem so that we can continue generating a FakeIngressServer. 

Context: We got here because we had to upgrade lager, which meant that we have to upgrade [ginkgo to v2](https://github.com/cloudfoundry/lager/pull/54) everywhere in diego-release, which then meant we had to upgrade from [go-loggregator v8](https://github.com/cloudfoundry/go-loggregator/blob/v8.0.5/go.mod#L19) to [v9](https://github.com/cloudfoundry/go-loggregator/blob/v9.0.4/go.mod), which then meant we had to upgrade [diego-logging-client](https://github.com/cloudfoundry/diego-logging-client/blob/main/go.mod#L6), which then meant we can no longer generate FakeIngressServer.

Do you have any suggestion for a workaround or other solution for this problem?

**Comment by winkingturtle-vmw** [comment]
We were able to remain on v8 and get the subset of the tests that were failing to pass, but this remain to be an issue to upgrade to v9.

**Comment by ctlong** [comment]
Hey @winkingturtle-vmw, sorry for the late response. Is this still a problem?

The reason for the change is a gRPC breaking change allowing generated files to be updated without requiring updates to server implementations. You can find this change discussed in more details here:
* https://stackoverflow.com/questions/65079032/grpc-with-mustembedunimplemented-method
* https://github.com/grpc/grpc-go/issues/3669

You should be able to resolve the diego-logging-client compilation error, and update to go-loggregator v9, by embedding [`UnimplementedIngressServer`](https://github.com/cloudfoundry/go-loggregator/blob/bb61a3684ff1b4168da109a24ef5b1f01f5e4a7a/rpc/loggregator_v2/ingress_grpc.pb.go#L126C6-L126C32) or [`UnsafeIngressServer`](https://github.com/cloudfoundry/go-loggregator/blob/bb61a3684ff1b4168da109a24ef5b1f01f5e4a7a/rpc/loggregator_v2/ingress_grpc.pb.go#L143C6-L143C25) in your `FakeIngressServer` struct. We recommend embedding the former.
