### ISSUE TITLE
IngressClient.EmitLog batching messages by default can be confusing

### ISSUE THREAD

**Issue by cnelson** [cloudfoundry/go-loggregator#18]
When using IngressClient, if the application exits before `batchFlushInterval` time has elapsed after calling `EmitLog() `the message will never be delivered because `EmitLog()` doesn't immediately send the message, but [batches requests and delivers them at some point in the future.](https://github.com/cloudfoundry-incubator/go-loggregator/blob/17682e3bc1157ea3b83e292ef6ee974ba992918c/ingress_client.go#L305-L321)

I attempted to work around this by configuring the client using `WithBatchMaxSize(0)` but this didn't seem to help.

What's the recommended way to immediately deliver a single message without relying on `time.Sleep()`?

Thanks!

**Comment by jasonkeene** [comment]
Some possible solutions:

- Just document the behavior and recommend using `RawClient` for direct sending of messages.
- Expose a method on the client that blocks until the active batch as been flushed. This would be good to allow for users to implement drain and die behaviour.
- Make batching optional via a `WithBatchingDisabled` option.
- Expose additional methods for direct sending of messages that bypass batching.

We will discuss what we want to do when this is IPM'ed. Thanks for filing the issue!

**Comment by JohannaSmith** [comment]
@cnelson  We have added a [`CloseSend()`](https://github.com/cloudfoundry/go-loggregator/blob/77235d73e3bb4c321a9fa7c4b3f8de6a64fd1cbf/ingress_client.go#L282) method to the IngressClient that will flush the buffers and close the stream to Metron. This method will block until the streams have been flushed.
