### ISSUE TITLE
Stop duplicating conversion logic

### ISSUE THREAD

**Issue by enocom** [cloudfoundry/go-loggregator#19]
See [here](https://github.com/cloudfoundry/loggregator/blob/ad62b351ceb8962ead1dced502560fab5450d0f1/src/code.cloudfoundry.org/loggregator/plumbing/conversion/tov1.go) and [here](https://github.com/cloudfoundry/loggregator/blob/ad62b351ceb8962ead1dced502560fab5450d0f1/src/code.cloudfoundry.org/loggregator/plumbing/conversion/tov1.go).

Conversion logic should be shared, not duplicated.

**Comment by bradylove** [comment]
@enocom The only way we can do that is if we share protobuf definitions as well and there are issues of using go-loggregator inside loggregator.

In order to use go-loggregator in loggregator we will have to move all protobuf definitions (mainly doppler) to go-loggregator.
