### ISSUE TITLE
Ingress client test fails sporadically

### ISSUE THREAD

**Issue by enocom** [cloudfoundry/go-loggregator#21]
The test server seems to be the root of the problem.

@jvshahid has a fix. See [here](https://github.com/cloudfoundry/diego-logging-client/commit/0c2722167a126e21f1f4828b45a3ce696023d107).

**Comment by bradylove** [comment]
@enocom That test server is no longer part of go-loggregator. It was removed when diego-logging-client was created.

I do see a failure a couple days ago on CI, I will dig into that and see what I can find.

**Comment by bradylove** [comment]
The error I was able to reproduce locally and on CI was:

```

  Expected error:
      <*status.statusError | 0xc420376420>: {
          Code: 1,
          Message: "context canceled",
          Details: nil,
      }
      rpc error: code = Canceled desc = context canceled
  not to have occurred
```
9efff0a4d476dbdef64c5cf8719843e1d999fc33 appears to have fixed it.
