### ISSUE TITLE
Example docs are out of date

### ISSUE THREAD

**Issue by jasonkeene** [cloudfoundry/go-loggregator#22]
These need to be updated:

https://github.com/cloudfoundry/go-loggregator/tree/041998b54f880b3e5460fcc4e7d4d77742dc3d86#example

For instance `examples/main.go` doesn't exist anymore.

**Comment by hdub2** [comment]
An example documenting the use of the streamConnector would be great!

**Comment by bradylove** [comment]
Updated the documentation and added an example for the envelope stream connector.
