### ISSUE TITLE
Close envelope_stream_connector gracefully when selector subcription changes

### ISSUE THREAD

**Issue by cdlliuy** [cloudfoundry/go-loggregator#24]
**User scenario:** 
We have interests in fetch container metrics & http start/stop from v2 API with selector subscription.  
Referring to the code 
https://github.com/cloudfoundry/go-loggregator/blob/master/examples/envelope_stream_connector/main.go
we can open a stream with the fixed selector, but the connection can't be closed easily if the selector changes on the fly.

For example,  we subscribed the metrics for appA and appB at first, then after a while,  we would like to subscribe the metrics for appB and appC.  In this case, we would like to close previously connection, and open a new one for the new subscription.

**Issue found:**
The envelope_stream_connector implementation (https://github.com/cloudfoundry/go-loggregator/blob/master/envelope_stream_connector.go ) doesn't expose a method to client to close the stream. 
This is the issue I hope to addressed here.

**Further Concern:**
For above user scenario, if we choose to close the staled connection and issue a new one , there is a probability that some of the metrics of appB maybe lost during the connection switch.  Is that possible to modify the subscription on the fly ?

**Comment by ahevenor** [comment]
@cdlliuy thanks for this feedback. It seems reasonable for us to at least provide an interface to close the stream. That said we are working on a new set of [API's called log-cache](https://github.com/cloudfoundry/log-cache) that might be worth investigating as well. It is not yet in GA for cf-deployment but we hope to accomplish that soon.

**Comment by cdlliuy** [comment]
@ahevenor ,  the log-cache looks much easier to consume (with Restful APIs and user token auth) than using the event stream connector directly .   Hope it would be ready as early as possible, so that we can adopt from v1 API to log-cache directly.

**Comment by ahevenor** [comment]
@cdlliuy - I would consider it stable and safe to develop against. We are close to making it generally available and you can follow along our progress towards GA with this [release marker](https://www.pivotaltracker.com/story/show/156278768). I am going to leave this request in our icebox for now.

**Comment by apoydence** [comment]
Closing due to age. Feel free to reopen.
