### ISSUE TITLE
There is no WithEventSourceInfo EmitEventOption

### ISSUE THREAD

**Issue by thepeterstone** [cloudfoundry/go-loggregator#28]
We have `WithSourceInfo` (which is an EmitLogOption), `WithCounterSourceInfo`, `WithGaugeSourceInfo` and `WithTimerSourceInfo`, but there is no EmitEventOption corollary.

**Comment by colins** [comment]
@thepeterstone how would you like to use `WithEventSourceInfo` if it existed? We haven't expanded it up until now for lack of use case.

**Comment by hdub2** [comment]
@colins the same as `WithGaugeSourceInfo` - right now we have 

```
func setSourceInfo(sourceID, instanceID string) loggregator.EmitEventOption {
  return func(message proto.Message) {
    switch e := message.(type) {
    case *loggregator_v2.Envelope:
      e.SourceId = sourceID
      e.InstanceId = instanceID
    default:
      log.Logger.Panic(fmt.Sprintf("unsupported Message type: %T", message))
    }
  }
}
``` 
which is a bit unwieldy.
