### ISSUE TITLE
How to execute the examples without a local metron agent?

### ISSUE THREAD

**Issue by scottschulthess** [cloudfoundry/go-loggregator#34]
Hello, not sure if this it the correct place for this question, but to test locally writing code that emits to a loggregator, you would typically want to emit on localhost 3457 to a metron agent, but if you are testing on your laptop how do you simulate this?  Is the best way an ssh tunnel into a bosh vm with metron agent or is there some other way to execute the samples?   Thanks!

**Comment by malston** [comment]
Hi @scottschulthess 
You can do that or you can [scp](https://bosh.io/docs/cli-v2/#ssh-mgmt) the example over to the machine that metron is on.

**Comment by scottschulthess** [comment]
Thanks @malston !
