### ISSUE TITLE
Expose pulseemitter through ingress client

### ISSUE THREAD

**Issue by kitemongerer** [cloudfoundry/go-loggregator#36]
It would be super cool if the pulseemitter functionality was exposed through the ingress client so that we could interact with gauges and counters in the same way as timers and events

**Comment by apoydence** [comment]
I think the `PulseEmitter` and the `IngressClient` are two separate concerns and should probably remain as such. I think we have landed on avoiding the "one type to rule them all" as it seems to lead to unwieldy code. If you are concerned/against passing in multiple things into a function then I would suggest wrapping them in a struct:

```
type LogClient struct {
  PulseEmitter
  IngressClient
}
```

This allows you to access the methods directly for both the `PulseEmitter` and `IngressClient` (much like I believe you are asking for). This pattern a preferred way of "puzzle piecing" types together that are related for the given use case.
