### ISSUE TITLE
return error after retry to stream too many times?

### ISSUE THREAD

**Issue by qibobo** [cloudfoundry/go-loggregator#40]
I write some code according to the example(https://github.com/cloudfoundry/go-loggregator/blob/master/examples/envelope_stream_connector/main.go)
One problem is that when there is some error in the tlsConfig, the stream will fail and it continuously retry and print out too many error logs.
My question is that is it possible to set a max-retry time so that after max-retry it will return error?
```
streamConnector := loggregator.NewEnvelopeStreamConnector(
		os.Getenv("LOGS_API_ADDR"),
		tlsConfig,
		loggregator.WithEnvelopeStreamLogger(loggr),
	)
```

**Comment by MasslessParticle** [comment]
It doesn't look like we've got control over the retry/connection. That's all handled by gRPC: https://github.com/cloudfoundry/go-loggregator/blob/cd9df093b3b104b3ee4bf1dda1c00661e1eaf6e9/envelope_stream_connector.go#L134-L143. The EnvelopeStreamConnector does accept grpc DialOptions, though. https://godoc.org/google.golang.org/grpc#DialOption . It looks like some of these control retries.

Other than that, you can control the timeout manually by manipulating the context on this line: https://github.com/cloudfoundry/go-loggregator/blob/cd9df093b3b104b3ee4bf1dda1c00661e1eaf6e9/examples/envelope_stream_connector/main.go#L58
