### ISSUE TITLE
Vendored types in interfaces break non-module builds

### ISSUE THREAD

**Issue by PeterFeicht** [cloudfoundry/go-loggregator#41]
The recent introduction of vendored libraries whose types are used in go-loggregator interfaces (in https://github.com/cloudfoundry/go-loggregator/commit/78f871c45ee3690736b1287edfd9f39ae8fb5baa) breaks non-module builds of libraries which use go-loggregator. For example, building an app that uses [diego-logging-client](https://github.com/cloudfoundry/diego-logging-client) results in the following error:
```
# code.cloudfoundry.org/diego-logging-client
src/code.cloudfoundry.org/diego-logging-client/client.go:99:64: cannot use "google.golang.org/grpc".WithBlock() (type "google.golang.org/grpc".DialOption) as type "code.cloudfoundry.org/go-loggregator/vendor/google.golang.org/grpc".DialOption in argument to loggregator.WithDialOptions:
        "google.golang.org/grpc".DialOption does not implement "code.cloudfoundry.org/go-loggregator/vendor/google.golang.org/grpc".DialOption (missing "code.cloudfoundry.org/go-loggregator/vendor/google.golang.org/grpc".apply method)
src/code.cloudfoundry.org/diego-logging-client/client.go:99:84: cannot use "google.golang.org/grpc".WithTimeout(time.Second) (type "google.golang.org/grpc".DialOption) as type "code.cloudfoundry.org/go-loggregator/vendor/google.golang.org/grpc".DialOption in argument to loggregator.WithDialOptions:
        "google.golang.org/grpc".DialOption does not implement "code.cloudfoundry.org/go-loggregator/vendor/google.golang.org/grpc".DialOption (missing "code.cloudfoundry.org/go-loggregator/vendor/google.golang.org/grpc".apply method)
```
This is caused by using the vendored `grpc.DialOption` as a parameter type here: https://github.com/cloudfoundry/go-loggregator/blob/78f871c45ee3690736b1287edfd9f39ae8fb5baa/ingress_client.go#L22

Builds using modules still work, because then vendored libraries are ignored. From what I could find, it doesn't seem to be a good idea to have vendored types in interfaces (see [this SO answer](https://stackoverflow.com/a/38288570/)).

**Comment by kitemongerer** [comment]
@PeterFeicht I think this should fix it https://github.com/cloudfoundry/go-loggregator/commit/049b6bf8152ab1ef57c13f4512be4754e4082faf

**Comment by PeterFeicht** [comment]
That was fast, thanks a lot!
