### ISSUE TITLE
RFE: Better error handling for RLPGatewayClient

### ISSUE THREAD

**Issue by bkabrda** [cloudfoundry/go-loggregator#42]
Hey 👋! I'm working on porting datadog-firehose-nozzle to loggregator V2 API [1]. With the `noaa/consumer` package for V1, we instantiated `FilteredFirehose` which returned channel with messages (envelopes) and also channel with errors. We could then have custom logic reacting to the errors (emitting custom logging messages etc). Additionally, we were able to use methods like `SetMaxRetryCount` to make the nozzle fail if there's e.g. a configuration problem and the URL we're trying to connect to has a typo in it.

The `RLPGatewayClient` structure has no means of sending errors and/or setting a maximum count of connection retries. This means that we have no way of customizing error behavior (either through reading some sort of channel with errors *or* using specialized methods like `SetMaxRetryCount`).

The biggest issue with the current codebase is that if user misconfigures the nozzle, it will keep trying to connect forever, which it shouldn't. A misconfigured nozzle should fail (soon-ish). The smaller issue is that we have no way of customizing what error messages will look like and at what levels they will be printed.

Would it be possible to add either a channel with errors or the specialized methods for error handling (or, ideally, both)? I realize that this RFE might in fact result in implementation of two unrelated features, but I hope that's ok for you as I see them very related.

Thanks for considering!

[1] https://github.com/DataDog/datadog-firehose-nozzle/pull/71

**Comment by gallo-cedrone** [comment]
I had the very same issue, this function should at least return an error that stream can report back to someone calling it, otherwise if misconfigured the client will try forever to connect:

``` go
func (c *RLPGatewayClient) connect(
	ctx context.Context,
	es chan<- *loggregator_v2.Envelope,
	logReq *loggregator_v2.EgressBatchRequest,
)
```

**Comment by pianohacker** [comment]
@bkabrda @gallo-cedrone We did some recent work to fix the infinite-retries behavior (https://github.com/cloudfoundry/go-loggregator/commit/ed037a13d8ec3e335846348faa8d96daea07ebeb) and add custom logging (https://github.com/cloudfoundry/go-loggregator/commit/c3d148141722ef54874659a54f1621bbd01a629d). We believe that these help the visibility and behavior of a failing RLP Gateway connection, but that the remaining ask is for a custom callback (or other notification) when the retries are exceeded and the client is permanently unhealthy. Is that correct?

**Comment by bkabrda** [comment]
@pianohacker thanks! Yes, that is correct (at least that's my ask, I can't speak for @gallo-cedrone)

**Comment by pianohacker** [comment]
Excellent! We have added that in https://github.com/cloudfoundry/go-loggregator/commit/3b3c7567591d7c217a33a511122fc186a5d8d1f7 . Closing this for now, but please follow up if there's anything we missed.
