### ISSUE TITLE
RFE: Enable logging with gosteno Logger from RLPGatewayClient

### ISSUE THREAD

**Issue by bkabrda** [cloudfoundry/go-loggregator#43]
Hey 👋! I'm working on porting datadog-firehose-nozzle to loggregator V2 API [1]. I noticed that it's possible to add a `log` object to the `NewRLPGatewayClient` function to get logs from the underlying logic. I'd like to request adding an option to add a gosteno Logger, as (IIUC) this is a logging implementation used/developed for cloudfoundry purposes and thus it would be nice to get it supported.

Note that for our usecase, it would also be sufficient to implement a channel with errors that the RLPGatewayClient would be pushing to and we could read from it and do the logging ourselves. I requested this in [2]. (Although technically the errors channel would not be useful for debug/info logs, so this would be useful either way.)

Thanks for considering!

[1] DataDog/datadog-firehose-nozzle#71
[2] https://github.com/cloudfoundry/go-loggregator/issues/42

**Comment by pianohacker** [comment]
This should be fixed in https://github.com/cloudfoundry/go-loggregator/commit/c3d148141722ef54874659a54f1621bbd01a629d .
