### ISSUE TITLE
Tests should pass

### ISSUE THREAD

**Issue by aminjam** [cloudfoundry/go-loggregator#50]
While working on updating downstream consumers (e.g. code.cloudfoundry.org/diego-logging-client), I noticed the following items are not working for this repo:

- Tests fails to run with Go 1.16.x. This is very likely due to certs generated without SANs
-  [rfc5424 is integrated](https://github.com/cloudfoundry/go-loggregator/commit/5adba004bd0139991d9e89899c0ceeb92db75054) in this repo and the downstream [rfc5424](https://github.com/cloudfoundry-incubator/rfc5424) is marked as archived, but none of the changes has been released. 
- The [latest tag 8.0.4](https://github.com/cloudfoundry/go-loggregator/tree/8.0.4) is missing a `v`. The tag should be in the format of `v8.0.4`. This is causing go modules failing to pull the latest changes
- This repo could use a [dependabot](https://github.com/cloudfoundry/archiver/blob/master/.github/dependabot.yml) and [github-action ci](https://github.com/cloudfoundry/archiver/blob/master/.github/workflows/go.yml) for running tests and bumping dependencies independently outside of other releases.
- Go mod version should be upgraded [from Go 1.12](https://github.com/cloudfoundry/go-loggregator/blob/5adba004bd0139991d9e89899c0ceeb92db75054/go.mod#L3) to Go 1.16

**Comment by Benjamintf1** [comment]
tests pass, and upped version of go in gomod.
